apiVersion: v1
kind: Service
metadata:
  name: v2ray-okteto
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: v2ray-okteto