apiVersion: v1
kind: Service
metadata:
  name: proxypool-okteto
spec:
  type: NodePort
  ports:
    - name: proxypool-okteto
      port: 443
      targetPort: 8080
  selector:
    app: proxypool-okteto