apiVersion: v1
kind: Service
metadata:
  name: proxypool-okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: proxypool-okteto
      port: 12580
  selector:
    app: proxypool-okteto